trigger:
  branches:
    include:
    - main
  paths:
    include:
    - apps/frontend/**
    - azure-pipelines-frontend.yml
    - devops/azure/pipelines/frontend.yml

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: devops/azure/pipelines/frontend.yml
