trigger:
  branches:
    include:
      - main
  paths:
    include:
      - apps/backend/**
      - azure-pipelines-backend.yml
      - devops/azure/pipelines/backend.yml

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: devops/azure/pipelines/backend.yml
