/*
  Design-time metadata prerequisite for the application Azure SQL database.

  This creates only the two approved configuration tables used before target
  execution. Target-resident metadata is generated by the pipeline and created
  later by Metadata Setup Execution.
*/

IF SCHEMA_ID(N'metadata') IS NULL
    EXEC(N'CREATE SCHEMA [metadata]');

IF OBJECT_ID(N'[metadata].[cfg_ingestion_object]', N'U') IS NULL
BEGIN
    CREATE TABLE [metadata].[cfg_ingestion_object] (
        ingestion_object_id BIGINT NULL,
        source_system_id BIGINT NULL,
        connection_id BIGINT NULL,
        object_kind NVARCHAR(100) NULL,
        ingestion_type NVARCHAR(100) NULL,
        processing_stage NVARCHAR(100) NULL,
        source_layer NVARCHAR(100) NULL,
        target_layer NVARCHAR(100) NULL,
        object_name NVARCHAR(1000) NULL,
        object_type NVARCHAR(100) NULL,
        source_resource_type NVARCHAR(100) NULL,
        payload_format NVARCHAR(100) NULL,
        container_format NVARCHAR(100) NULL,
        source_path NVARCHAR(MAX) NULL,
        file_pattern NVARCHAR(1000) NULL,
        database_schema NVARCHAR(512) NULL,
        table_name NVARCHAR(512) NULL,
        query_text NVARCHAR(MAX) NULL,
        endpoint_path NVARCHAR(MAX) NULL,
        http_method NVARCHAR(32) NULL,
        request_headers_json NVARCHAR(MAX) NULL,
        request_params_json NVARCHAR(MAX) NULL,
        request_body_template NVARCHAR(MAX) NULL,
        response_root_path NVARCHAR(1000) NULL,
        pagination_type NVARCHAR(100) NULL,
        pagination_config_json NVARCHAR(MAX) NULL,
        parser_options_json NVARCHAR(MAX) NULL,
        normalization_options_json NVARCHAR(MAX) NULL,
        schema_inference_policy NVARCHAR(100) NULL,
        schema_evolution_policy NVARCHAR(100) NULL,
        load_type NVARCHAR(100) NULL,
        watermark_column NVARCHAR(512) NULL,
        boundary_operator NVARCHAR(100) NULL,
        tie_breaker_columns_json NVARCHAR(MAX) NULL,
        sort_columns_json NVARCHAR(MAX) NULL,
        lookback_interval NVARCHAR(100) NULL,
        checkpoint_type NVARCHAR(100) NULL,
        target_bronze_table NVARCHAR(1000) NULL,
        target_silver_table NVARCHAR(1000) NULL,
        target_gold_table NVARCHAR(1000) NULL,
        target_table NVARCHAR(1000) NULL,
        write_mode NVARCHAR(100) NULL,
        merge_keys_json NVARCHAR(MAX) NULL,
        dedupe_keys_json NVARCHAR(MAX) NULL,
        partition_columns_json NVARCHAR(MAX) NULL,
        delete_strategy NVARCHAR(100) NULL,
        scd_config_json NVARCHAR(MAX) NULL,
        dependency_objects_json NVARCHAR(MAX) NULL,
        validation_policy_json NVARCHAR(MAX) NULL,
        execution_spec_json NVARCHAR(MAX) NULL,
        config_hash NVARCHAR(128) NULL,
        config_version INT NULL,
        effective_from DATETIME2(6) NULL,
        effective_to DATETIME2(6) NULL,
        is_current BIT NULL,
        active_flag BIT NULL,
        created_at DATETIME2(6) NULL,
        updated_at DATETIME2(6) NULL
    );
END;

IF OBJECT_ID(N'[metadata].[cfg_mapping]', N'U') IS NULL
BEGIN
    CREATE TABLE [metadata].[cfg_mapping] (
        mapping_id BIGINT NULL,
        ingestion_object_id BIGINT NULL,
        processing_stage NVARCHAR(100) NULL,
        source_layer NVARCHAR(100) NULL,
        target_layer NVARCHAR(100) NULL,
        source_object_name NVARCHAR(1000) NULL,
        target_object_name NVARCHAR(1000) NULL,
        target_table NVARCHAR(1000) NULL,
        mapping_group NVARCHAR(512) NULL,
        transformation_group NVARCHAR(512) NULL,
        input_objects_json NVARCHAR(MAX) NULL,
        join_rules_json NVARCHAR(MAX) NULL,
        aggregation_rules_json NVARCHAR(MAX) NULL,
        build_order INT NULL,
        source_field_path NVARCHAR(1000) NULL,
        source_data_type NVARCHAR(512) NULL,
        target_column_name NVARCHAR(512) NULL,
        target_data_type NVARCHAR(512) NULL,
        is_nullable BIT NULL,
        is_array BIT NULL,
        is_primary_key BIT NULL,
        transformation_rule NVARCHAR(MAX) NULL,
        transformation_language NVARCHAR(100) NULL,
        default_value NVARCHAR(MAX) NULL,
        ordinal_position INT NULL,
        validation_rule_json NVARCHAR(MAX) NULL,
        severity NVARCHAR(100) NULL,
        failure_action NVARCHAR(100) NULL,
        threshold_value FLOAT NULL,
        threshold_unit NVARCHAR(100) NULL,
        stop_watermark_on_failure BIT NULL,
        mapping_hash NVARCHAR(128) NULL,
        mapping_version INT NULL,
        effective_from DATETIME2(6) NULL,
        effective_to DATETIME2(6) NULL,
        is_current BIT NULL,
        active_flag BIT NULL,
        created_at DATETIME2(6) NULL,
        updated_at DATETIME2(6) NULL
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_cfg_ingestion_object_version'
      AND object_id = OBJECT_ID(N'[metadata].[cfg_ingestion_object]')
)
    CREATE UNIQUE INDEX UX_cfg_ingestion_object_version
        ON [metadata].[cfg_ingestion_object] (ingestion_object_id, config_version);

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_cfg_mapping_version'
      AND object_id = OBJECT_ID(N'[metadata].[cfg_mapping]')
)
    CREATE UNIQUE INDEX UX_cfg_mapping_version
        ON [metadata].[cfg_mapping] (mapping_id, mapping_version);
