-- Replace __TARGET_CATALOG__ with a validated Unity Catalog catalog name.
CREATE SCHEMA IF NOT EXISTS __TARGET_CATALOG__.metadata_schema;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.cfg_source_system (
    source_system_id BIGINT,
    source_system_name STRING,
    business_domain STRING,
    owner_name STRING,
    owner_email STRING,
    description STRING,
    active_flag BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.cfg_connection (
    connection_id BIGINT,
    source_system_id BIGINT,
    connection_name STRING,
    connection_type STRING,
    connection_contract_name STRING,
    connection_schema_version STRING,
    host_name STRING,
    port INT,
    base_path STRING,
    base_url STRING,
    database_name STRING,
    auth_type STRING,
    secret_scope STRING,
    secret_key STRING,
    secrets_json STRING,
    config_json STRING,
    config_hash STRING,
    config_version INT,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    is_current BOOLEAN,
    active_flag BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.cfg_ingestion_object (
    ingestion_object_id BIGINT,
    source_system_id BIGINT,
    connection_id BIGINT,
    object_kind STRING,
    ingestion_type STRING,
    processing_stage STRING,
    source_layer STRING,
    target_layer STRING,
    object_name STRING,
    object_type STRING,
    source_resource_type STRING,
    payload_format STRING,
    container_format STRING,
    source_path STRING,
    file_pattern STRING,
    database_schema STRING,
    table_name STRING,
    query_text STRING,
    endpoint_path STRING,
    http_method STRING,
    request_headers_json STRING,
    request_params_json STRING,
    request_body_template STRING,
    response_root_path STRING,
    pagination_type STRING,
    pagination_config_json STRING,
    parser_options_json STRING,
    normalization_options_json STRING,
    schema_inference_policy STRING,
    schema_evolution_policy STRING,
    load_type STRING,
    watermark_column STRING,
    boundary_operator STRING,
    tie_breaker_columns_json STRING,
    sort_columns_json STRING,
    lookback_interval STRING,
    checkpoint_type STRING,
    target_bronze_table STRING,
    target_silver_table STRING,
    target_gold_table STRING,
    target_table STRING,
    write_mode STRING,
    merge_keys_json STRING,
    dedupe_keys_json STRING,
    partition_columns_json STRING,
    delete_strategy STRING,
    scd_config_json STRING,
    dependency_objects_json STRING,
    validation_policy_json STRING,
    execution_spec_json STRING,
    config_hash STRING,
    config_version INT,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    is_current BOOLEAN,
    active_flag BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.cfg_mapping (
    mapping_id BIGINT,
    ingestion_object_id BIGINT,
    processing_stage STRING,
    source_layer STRING,
    target_layer STRING,
    source_object_name STRING,
    target_object_name STRING,
    target_table STRING,
    mapping_group STRING,
    transformation_group STRING,
    input_objects_json STRING,
    join_rules_json STRING,
    aggregation_rules_json STRING,
    build_order INT,
    source_field_path STRING,
    source_data_type STRING,
    target_column_name STRING,
    target_data_type STRING,
    is_nullable BOOLEAN,
    is_array BOOLEAN,
    is_primary_key BOOLEAN,
    transformation_rule STRING,
    transformation_language STRING,
    default_value STRING,
    ordinal_position INT,
    validation_rule_json STRING,
    severity STRING,
    failure_action STRING,
    threshold_value DOUBLE,
    threshold_unit STRING,
    stop_watermark_on_failure BOOLEAN,
    mapping_hash STRING,
    mapping_version INT,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    is_current BOOLEAN,
    active_flag BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.ctl_ingestion_queue (
    queue_id BIGINT,
    ingestion_object_id BIGINT,
    trigger_type STRING,
    queue_status STRING,
    priority INT,
    logical_work_id STRING,
    idempotency_key STRING,
    work_scope_json STRING,
    requested_start_boundary STRING,
    requested_end_boundary STRING,
    partition_spec_json STRING,
    batch_id STRING,
    requested_by STRING,
    manual_override_json STRING,
    requested_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    claimed_by_worker_id STRING,
    lease_acquired_at TIMESTAMP,
    lease_expires_at TIMESTAMP,
    last_heartbeat_at TIMESTAMP,
    attempt_count INT,
    max_attempts INT,
    next_retry_at TIMESTAMP,
    retry_policy_json STRING,
    metadata_snapshot_id STRING,
    run_id STRING,
    message STRING
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.ctl_run (
    run_id STRING,
    queue_id BIGINT,
    attempt_number INT,
    logical_work_id STRING,
    idempotency_key STRING,
    ingestion_object_id BIGINT,
    source_system_id BIGINT,
    connection_id BIGINT,
    ingestion_type STRING,
    processing_stage STRING,
    source_layer STRING,
    target_layer STRING,
    target_table STRING,
    write_mode STRING,
    notebook_name STRING,
    pipeline_name STRING,
    metadata_snapshot_id STRING,
    connection_config_version INT,
    ingestion_object_config_version INT,
    mapping_version INT,
    metadata_hash STRING,
    source_boundary_hash STRING,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status STRING,
    current_phase STRING,
    phase_status_json STRING,
    rows_read BIGINT,
    rows_written BIGINT,
    files_processed BIGINT,
    bytes_processed BIGINT,
    execution_time_seconds DOUBLE,
    target_write_id STRING,
    target_commit_status STRING,
    validation_status STRING,
    validation_summary_json STRING,
    watermark_before STRING,
    watermark_after STRING,
    watermark_commit_status STRING,
    recovery_action STRING,
    created_at TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.ctl_error_log (
    error_id STRING,
    run_id STRING,
    queue_id BIGINT,
    attempt_number INT,
    ingestion_object_id BIGINT,
    source_system_id BIGINT,
    connection_id BIGINT,
    error_stage STRING,
    error_phase STRING,
    error_code STRING,
    error_message STRING,
    error_detail STRING,
    severity STRING,
    retryable_flag BOOLEAN,
    retry_action STRING,
    error_time TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS __TARGET_CATALOG__.metadata_schema.ctl_watermark (
    watermark_id BIGINT,
    ingestion_object_id BIGINT,
    watermark_type STRING,
    watermark_column STRING,
    last_watermark_value STRING,
    committed_watermark_value STRING,
    candidate_watermark_value STRING,
    candidate_run_id STRING,
    candidate_created_at TIMESTAMP,
    last_successful_run_id STRING,
    watermark_version BIGINT,
    commit_status STRING,
    boundary_operator STRING,
    tie_breaker_value_json STRING,
    checkpoint_state_json STRING,
    committed_at TIMESTAMP,
    updated_at TIMESTAMP
) USING DELTA;
